version: "3.3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_USER: 'devops'
      MYSQL_ROOT_PASSWORD: 'devops'
      MYSQL_DATABASE: 'tpachato'
      MYSQL_ROOT_HOST: '%'
      MYSQL_PASSWORD: 'devops'
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  spring_app:
    image: maneeel/tp-achat
    container_name: tp-achat
    restart: on-failure
     environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.username" : "devops",
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tpachato?useSSL=false",
        "spring.datasource.password" : "devops"
      }'
    ports:
      - 8089:8089
    
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    depends_on:
      - mysqldb
volumes:
  db:            
