version: '3.9'
services:
  mysqldb:
    container_name: mysqlislem
    image: "mysql:latest"
    restart: "on-failure"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - '/home/mysql-data:/var/lib/mysql'
  spring_app:
    image: "islemchatti/islemrepo"
    container_name: devopsIslemchatti
    restart: "on-failure"
    ports:
      - "9090:9090"
    depends_on:
      - mysqldb
