version: "3"

services:
  mysqldb:
    container_name: mysqldbtp
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: 'tpachatdb'
      MYSQL_USER: 'root'
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes:
      - /home/mysql/data:/var/lib/mysql
  spring_app:
    image: maneeel/tp-achat
    container_name: tp-achat
    restart: on-failure
    ports:
      - 8089:8089
    
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    depends_on:
      - mysqldb            
